api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      additionalPortMappings:
        - targetPort: 8000
          external: false
        - targetPort: 8001
          external: false
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--storage
        value: storage:6379,password={{ securedParameter "storage_password" }}
  template:
    containers:
      - image: {{ .Image }}
        name: silo
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: Orleans__ClusterId
            value: '{{ parameter "orleans_cluster_id" }}'
          - name: Orleans__Clustering__ProviderType
            value: Redis
          - name: Orleans__Clustering__ServiceKey
            value: storage
          - name: Orleans__EnableDistributedTracing
            value: "true"
          - name: Orleans__Endpoints__GatewayPort
            value: "8001"
          - name: Orleans__Endpoints__SiloPort
            value: "8000"
          - name: Orleans__GrainStorage__Default__ProviderType
            value: Redis
          - name: Orleans__GrainStorage__Default__ServiceKey
            value: storage
          - name: Orleans__ServiceId
            value: '{{ parameter "orleans_service_id" }}'
          - name: ConnectionStrings__storage
            secretRef: connectionstrings--storage
    scale:
      minReplicas: 1
tags:
  azd-service-name: silo
  aspire-resource-name: silo
